name: main
description: A sample command-line application in a space theme.
version: 1.0.1

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
    # path: ^1.8.0
    intl: ^0.17.0

dev_dependencies:
    pedantic: ^1.10.0
    test: ^1.16.0

assets:
    - bin/planetarySystem.json
